name: Go release

on:
  release:
    types: [published]
    

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: windows/386, windows/amd64
        goos: [windows]
        goarch: ["386", amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Go release
        uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "csgohack"
          asset_name: csgohack-${{ matrix.goos }}-${{ matrix.goarch }}
          compress_assets: OFF
